version: '3.8'

services:
  webhook:
    build:
      context: ./src
    ports:
      - "5000:5000"
    environment:
      - GITHUB_SECRET=example-secret
    volumes:
      - ./src:/app
    depends_on:
      - db # If you have a database service